name: later_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_slidable: ^4.0.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/